### ISSUE TITLE
Nedlastingslenke mangler for eksempeldata i reg.-løsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/registration-portal#14]
Forhåndsvisning av datasett krever at nedlastingslenken er oppgitt. Dette feltet mangler for eksempeldata. For data som ikke er åpne data er eksempeldata svært nyttige metadata. 

https://github.com/Informasjonsforvaltning/dataset-catalog-gui/issues/226

**Comment by stigbd** [comment]
Er det dette feltet vi snakkar om:
https://data.norge.no/specification/dcat-ap-no/#Datasett-eksempeldata

**Comment by oystein-asnes** [comment]
Ja og nei. `adms:sample` er ein type `dcat:distribution`. Eksempeldata-distribusjonen kan dermed ha alle eigenskapar til `dcat:distribution`. I reg.løsninga er det i dag `beskrivelse`, `format `og `tilgangslenke`

**Comment by stigbd** [comment]
> Lenkesjekk for tilgangsURL og nelastingslenke (gjelder alle lenker i reg. skjemaet- ikke bare her)

Dette er gjennomførbart. To spørsmål:
1. Kva vil du skal skje dersom ein får noko anna enn 200 OK på denne?
2. Skal vi sjekke at content-type i respons matchar formatet som er oppgit? (Og kva skal skje dersom det ikkje matchar?)

**Comment by stigbd** [comment]
> Støtte for opplasting av eksempeldata
> Eksempeldata er metadata og jeg tar til orde for at vi støtter opplasting av eksempeldata i katalogen for noen formater (csv, json, xml, (xlsx) og med maks filstørrelse på feks 10 mb. Nåsituasjonen er at brukeren må legge eksempeldata ut på egen webserver og deretter peke dit.

Denne er litt tricky. Strengt tatt er jo eksempeldata ein dcat:Distribusjon. Så eg forstår deg dit at vi skal la brukar laste opp eit datasett, så genererer _vi_ ein distribusjons-instans, lastar opp datasettet til feks eksempel-data-server.data.norge.no, som vi har kontroll på, og setter downloadURL til å peike til ein path på denne serveren?

**Comment by stigbd** [comment]
Når det gjelder opplasting av eksempeldata: ei elegant løysing ville vere å bruke datahotellet (https://hotell.difi.no/) til å vere vert for eksempeldatan.

**Comment by shenluna** [comment]
Testet ok og prodsatt
