### ISSUE TITLE
Begrepskatalog: Veldig treg visning av antall hvis mye innhold

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/registration-portal#194]
Hvis man har et stort antall begrep i katalogen, vil det ta merkbart lang tid før antallet dukker opp i hovedoversikten.
Inntil man får svar fra concept-catalog/mongodb står det "0 begrep".
For en org med 8-9000 begrep, tar det ca 7 sekunder før antallet dukker opp.

- Hent antallet raskere
- Evt vis "spinner" e.l. istedet for "0 begrep"

**Comment by hegeaal** [comment]
Blir vanskelig å få det til å laste raskere, men har lagt til spinner (i catalog-portal)
